### ISSUE TITLE
Close MainMenuFloatingActionButton when FloatingActionButton is pressed

### ISSUE THREAD

**Issue by tropicoder** [MayLau-CbL/ArcSpeedDial#1]
Hi,

i want to Close MainMenuFloatingActionButton when FloatingActionButton is pressed. How can i do it ?

Regards,

**Comment by MayLau-CbL** [comment]
Hi @tropicoder ,
Currently, this library has a private boolean inside the widget to control the open-close of the MainMenuFloatingActionButton. I am planning to have an update to make the widget is available to control the open-close action by exposing that boolean the coming weekend. You may take a look later if that may fit you. :-)
