### ISSUE TITLE
FloatingActionButton work even when it is invisible.

### ISSUE THREAD

**Issue by SuTechs** [MayLau-CbL/ArcSpeedDial#2]
![image1](https://user-images.githubusercontent.com/49246806/85216342-039dc800-b3a1-11ea-8dc1-f5b793a66e60.jpeg)
![image2](https://user-images.githubusercontent.com/49246806/85216343-04cef500-b3a1-11ea-9dea-e9619042e341.jpeg)

When clicked on the marked locations, it triggers the hidden button. If the button is hidden, it should not work.

**Comment by MayLau-CbL** [comment]
Thank you for reporting! I can simulate that issue and will release a new version for that later.

**Comment by MayLau-CbL** [comment]
Update a new release v1.0.3 on pub.dev, you may take a look if this resolved the issue you facing.

**Comment by SuTechs** [comment]
It is working, thanks.
